### ISSUE TITLE
Is this gem meant to work side-by-side with 'react-rails' gem, or to replace it?

### ISSUE THREAD

**Issue by liorbrauer** [netguru/react_webpack_rails#10]
Hi,

It's not clear from the documentation how to incorporate the React object itself into the project. The most logical option I see is to expose it manually to `window.React` in my code after I do the

`import React from 'react'`

Is this what you intended? 

Thanks!

**Comment by mxaly** [comment]
Answering question from topic - it meant to replace `react-rails` gem.

For the React object - we are exposing it 'manually' to window.React 
https://github.com/netguru/react_webpack_rails/blob/master/lib/generators/react_webpack_rails/templates/react/index.js.erb#L1-L2

So if you are using install generator, it should work just fine. Is there a reason why you are trying to mix it with `react-rails` gem?

**Comment by liorbrauer** [comment]
@mxaly Since I didn't have the React object exposed by default I thought this gem might depend on `react-rails` to load it. Thanks!
