### ISSUE TITLE
deploy problems

### ISSUE THREAD

**Issue by kalashnikovisme** [netguru/react_webpack_rails#100]
Hi! I've add `NODE_ENV=production npm run build` and have error `webpack not found`. After installing webpack on server I have this errors

```
module.js:327
throw err;
Error: Cannot find module 'webpack' at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/srv/facebook/releases/20160527190908/webpack/production.config.js:1:79)  at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
Module.require (module.js:353:17)\n\nnpm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs/" "/usr/bin/npm" "run" "build"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! @ build: `webpack -p --config webpack/production.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'webpack -p --config webpack/production.config.js'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:\ssh nnpm ERR!     webpack -p --config webpack/production.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /srv/facebook/releases/20160527190908/npm-debug.log
```

Please, tell me, what I do wrong?

**Comment by 33volcanoes** [comment]
Same Problem +1

**Comment by mxaly** [comment]
Hi, trying to reproduce this and need a bit more info. 
What node version you have on your machine? 
Can you check if webpack is installed locally (`npm ls --depth=0`) and/or globally (`npm -g ls --depth=0`)?

**Comment by kalashnikovisme** [comment]
@mxaly Hi!

```
root:~# nodejs -v
v4.4.5
root:/srv/facebook/current# npm ls --depth=0
/srv/facebook/releases/20160522163403
└── webpack@1.13.1
root:/srv/facebook/current# npm -g ls --depth=0
/usr/lib
├── npm@2.15.5
└── webpack@1.13.1
```

**Comment by mxaly** [comment]
Hmm, only webpack there? 
`npm run build` is running webpack but other npm libs (listed in `package.json`) still need to be installed. 

I can see that you are using capistrano there, is that right? if so, adding `capistrano/npm` should solve this. Check for example here: https://github.com/netguru/props/blob/0c94eb49d63b403e9712543484514493e2f9e6de/Capfile#L4 or with docker here https://github.com/netguru/props/blob/master/Capfile#L5

**Comment by kalashnikovisme** [comment]
@mxaly I don't using capistrano, but ansible. I've added to deploy playbook `npm install`. And have such error

```
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN peerDependencies The peer dependency react@^15.1.0 included from react-addons-test-utils will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@^15.0.0 included from react-webpack-rails will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-dom@^15.0.0 included from react-webpack-rails will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.12
```

Please, tell me. which packages are responsible for this?
I'm new on this stack and experiencing difficulties during fix it. Thanks!

**Comment by mxaly** [comment]
looks like warnings only there - it's because of npm 3+ and it's changes. We will handle it shortly. Anyway, it should work for you after installing because nothing critical there. Is `npm run build` still complaining about missing `webpack`?

I don't have experience with ansible but i know who have - will talk to them tomorrow.

**Comment by kalashnikovisme** [comment]
@mxaly thnx very match!

**Comment by kalashnikovisme** [comment]
@mxaly any updates?

**Comment by mxaly** [comment]
Hi, sorry for delay. It looks like ansible should work just fine. Try running `npm install` manually and then see what  `npm run build` will return. If it will fail again, check if there are packages installed. 

also take a look at this: https://github.com/citrusbyte/cuba-skeleton/tree/master/ansible - it's including webpack assets compilation so some setup from it may be helpful

**Comment by kalashnikovisme** [comment]
@mxaly after updating npm to version 3 current problem was solved. But I have new problem while assets precompilation

```ruby
ExecJS::ProgramError: Unexpected token: operator (<) (line: 143, col: 13, pos: 3939)

Error  at new JS_Parse_Error (<eval>:2659:11936)
```

**Comment by kalashnikovisme** [comment]
`RAILS_ENV=production rake assets:precompile` had the same error until I commented this line in `config/environments/production.rb`

```
config.assets.js_compressor = :uglifier
```

Deploying production with not minified JS is not good idea :smile:

**Comment by mxaly** [comment]
hey @kalashnikovisme 
are you sure that you es6 code is isolated from rails assets? 

We have put all react/es6 code into `app/react` so sprockets (with default configuration) won't try to compile it. In your case it looks like there is something in `app/assets` written in es6 or sprockets configuration was changed so it's looking at `app/react` 

Webpack gives you output as pure JS - it should not be a problem for uglifier to compile that. We are doing it in different project without any problems.

**Comment by kalashnikovisme** [comment]
@mxaly Yes! You right. My ES6 code in app/assets/ folder. I think that's the problem. Closing.

Thanks very much!
