### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by aymericbouzy** [netguru/react_webpack_rails#101]
Wasn't sure how to tell you this other than publishing an issue : THANK YOU. I'm so grateful, I had been struggling to publish my react / rails app to heroku, and it works like a charm, with the added benefit of hot reloading. Thank you so much.

**Comment by nekath** [comment]
We are really happy seeing this :)

The best way to `say thank you` is to give us feedback on what do you like, what could be improved or changed :D

**Comment by aymericbouzy** [comment]
Sure I will !


Actually i do have a question : in rails, when providing an image asset,
you can use a helper. How would you recommend doing this in RWR ?


On 13 June 2016 at 08:00:24, Radosław Piątek (notifications@github.com)
wrote:

We are really happy seeing this :)

The best way to say thank you is to give us feedback on what do you like,
what could be improved or changed :D

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/netguru/react_webpack_rails/issues/101#issuecomment-224023454>,
or mute the thread
<https://github.com/notifications/unsubscribe/AHymFaW3_-1VcZHj9tnc_-_WyjQfsWfmks5qJFSrgaJpZM4IvFUo>
.

**Comment by mxaly** [comment]
related: https://github.com/netguru/react_webpack_rails/issues/61
