### ISSUE TITLE
Something funky with Forever load path configuration

### ISSUE THREAD

**Issue by drmanitoba** [netguru/react_webpack_rails#103]
Hi there. I'm trying to spin up the node server for SSR and Forever seems to be having trouble resolving the path to the server file. Without my making any changes to the `development.json` file, the error is:

```bash
Error: Cannot find module '/Users/my_user/my_app/app/react/app/react/node_server.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
error: Forever detected script exited with code: 1
```

Seems that the problem is that its not resolving the path properly. `/app/react/app/react/node_server.js` is obviously an extra two levels deep it doesn't need to go to.

I've tried modifying the `sourceDir` param in the development.json file to no avail. Any advice?

**Comment by drmanitoba** [comment]
Not sure where this bug comes from, but I got it working with the following config:

```json
{
  "uid": "rwr-node-server",
  "append": true,
  "script": "node_server.js",
  "workingDir": "./",
  "sourceDir": "app/react",
  "watch": true,
  "watchDirectory": "app/react"
}
```

**Comment by mxaly** [comment]
@drmanitoba looks like we need to review and update forever config. Thanks for posting solution :)

**Comment by drmanitoba** [comment]
Yeah I found some bug in the Forever repo's issues related to Forever's interpretation of the CWD. Definitely seems like its Forever's problem, not yours. :)
