### ISSUE TITLE
Path problem when launching npm run rwr-node-dev-server

### ISSUE THREAD

**Issue by gbarillot** [netguru/react_webpack_rails#108]
Hi,

After installing on a fresh new Rails (4.2) app, I get this when trying to launch "npm run rwr-node-dev-server" from the app root directory.

Error: Cannot find module '/Users/guillaume/www/react-rails/app/react/app/react/node_server.js'

Looks like the path is wrong cause it duplicates the "/app/react" section. I tried to edit "/forever/development.json" to fix it but no luck. Am I missing something? How can I fix the path to node_server.js?

Thanks.

EDIT: weird, but it works if I set the full absolute path in "/forever/development.json" instead of the relative one, like this : 

{
    "uid": "rwr-node-server",
    "append": true,
    "script": "node_server.js",
    "sourceDir": "/Users/guillaume/www/react-rails/app/react",
    "watch": true,
    "watchDirectory": "./app/react"
}

I'm using a Mac (El Capitan) + ZSH (oh-my-zsh). Could it be a shell/bash problem?

**Comment by mxaly** [comment]
hi @gbarillot 

We already have a fix for that, see https://github.com/netguru/react_webpack_rails/issues/103. 
Adding:  `"workingDir": "./",` to forever config will fix.

**Comment by gbarillot** [comment]
Perfect, thank you @mxaly , the fix in #103 works.
