### ISSUE TITLE
Turbolinks 5

### ISSUE THREAD

**Issue by thiagoc7** [netguru/react_webpack_rails#109]
Hello guys, thanks for this gem.
Is it supposed to work with rails 5 / turbolinks 5?

For me is not working:
![image](https://cloud.githubusercontent.com/assets/6671184/16949737/c81fd052-4d92-11e6-9270-88e1eedf577f.png)

but if I disable turbolinks it works.

Thanks!

**Comment by mxaly** [comment]
Hi!

yep, it should. Looks like something changed there, again. On it!

**Comment by thiagoc7** [comment]
Please let me know if I can help.

**Comment by mxaly** [comment]
Can if you have global `Turbolinks` accessible in your browser? if yes, is there something under `Turbolinks.controller`?

i have just updated to latest rails and turbolinks and can't reproduce this problem.

**Comment by thiagoc7** [comment]
Thanks @mxaly, if it's working for you, I'l try to reproduce this issue in a fresh app.
Anyway, I do have `Turbolinks` globaly, and that's the output:
![image](https://cloud.githubusercontent.com/assets/6671184/16957479/dbd72850-4db2-11e6-8df2-ba7ed592a86c.png)

**Comment by thiagoc7** [comment]
I have the same issue with a [new app](https://github.com/thiagoc7/test_rwr):

![image](https://cloud.githubusercontent.com/assets/6671184/16959707/bfa6b1e6-4dbc-11e6-9352-7f42934dee12.png)

**Comment by mxaly** [comment]
@thiagoc7 My bad, i was checking with master branch where it was fixed while 0.4 was broken. Update to 0.5.0 will solve this.

**Comment by thiagoc7** [comment]
Thanks!
