### ISSUE TITLE
problem with turbolinks

### ISSUE THREAD

**Issue by marcinkornek** [netguru/react_webpack_rails#11]
I created simple application with devise authentication and `react_webpack_rails`. After logging in application on `root_path` there is react component and it works fine, but when I go to other rails page (eg. user account) and move back to `root_path` with react it doesn't load react. It works only after refreshing page. I "fixed" this temporarily with deleting turbolinks from application but it should be other solution for this

**Comment by mxaly** [comment]
@marcinkornek i tested it out and looks like it's working fine in my apps so i decided to take a look at [your app](https://github.com/marcinkornek/home-budget-rails-react-redux) and found the problem - `//= require turbolinks` must be done before `//= require react_integration` 
There is [PR](https://github.com/marcinkornek/home-budget-rails-react-redux/pull/1) with fix waiting for merge :)
