### ISSUE TITLE
Deprecated links in the docs/README.md

### ISSUE THREAD

**Issue by goalaleo** [netguru/react_webpack_rails#112]
The `README.md` file in docs folder contains links to `ReactRouter`API.
<img width="378" alt="screenshot 2016-07-27 16 36 28" src="https://cloud.githubusercontent.com/assets/3275302/17177064/484b2f5c-5418-11e6-9329-1ab07b0fe12b.png">

However, the latest commit message implies that the content was removed from the api docs, and sure enough there's no mention about `react_router`in the api docs.

TODO: Remove "1.2 ReactRouter" and all the links under it from README.md

**Comment by mxaly** [comment]
done in #134
