### ISSUE TITLE
Style assets deployment

### ISSUE THREAD

**Issue by aymericbouzy** [netguru/react_webpack_rails#126]
I have been using RWR successfully on Heroku for a while. I started using `require('some_stylesheet.scss')` in my `.js` code, and all was fine in development environment. Then I pushed to Heroku, but saw that the styles I had defined in `some_stylesheet.scss` were missing. Indeed I am getting an error in my Browser console : 
`Failed to load resource: the server responded with a status of 404 (Not Found) https://instant-job-staging.herokuapp.com/tmp/build_a868f0dbfc615be088fe227fa3cbb765/app/assets/stylesheets/react_bundle.css`
I can see this is coming from one of the first lines in my `application-7ad1407724e47...88a06.css` file : 
`@import url(/tmp/build_a868f0dbfc615be088fe227fa3cbb765/app/assets/stylesheets/react_bundle.css);`

If my understanding is correct, this file is only present during precompile, so it's not a surprise that I should get a 404 error.

Maybe this error could come from the fact that I had included `require react_bundle` in my `app/assets/stylesheets/application.scss` file initially, but I have now removed it and it doesn't solve my problem.

Thanks for your help.

**Comment by aymericbouzy** [comment]
So I found the solution : 
You have to edit `config/initializers/assets.rb`, and add the following line : 
```rb
Rails.application.config.assets.precompile += %w( react_bundle.css )
```
then in the head of your html layout add : 
```erb
<%= stylesheet_link_tag 'react_bundle', media: 'all', 'data-turbolinks-track' => true %>
```
and it works on Heroku :)

**Comment by aymericbouzy** [comment]
Maybe it could be worth it to document that trick in the deployment readme.

**Comment by mxaly** [comment]
@aymericbouzy defentely. 

Just one question, Did you have `@import react_bundle` somewhere in your assets? for eg in `application.scss`?

**Comment by aymericbouzy** [comment]
Indeed, I had `@import "*";`
