### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by spherop** [netguru/react_webpack_rails#128]
Rails 5.0.0.1
Ruby 2.3.1

added gem to gemfile `gem 'react_webpack_rails'`

ran `bundle`

then: 
`rails g react_webpack_rails:install`
result:
`-bash: $: command not found`

**Comment by mxaly** [comment]
@spherop is that rails command that is missing? if yes, `bundle exec rails g react_webpack_rails:install` should solve this.

however, generator is also running `bundle install` & `npm install` as last step. make sore both commands are working fine

**Comment by spherop** [comment]
I have gotten install to work ... thanks for help!
