### ISSUE TITLE
TypeError: dispatcher.onPost is not a function

### ISSUE THREAD

**Issue by rubylibre** [netguru/react_webpack_rails#129]
When running the server rendering example I got the following error:
```
TypeError: dispatcher.onPost is not a function
```

Fixed it by doing this in app/react/node_server.js:
```
const HttpDispatcher   = require('httpdispatcher');
const dispatcher = new HttpDispatcher();
```

**Comment by mxaly** [comment]
@rubylibre thanks for reporting this!,
You must be using new httpdispather (2.x) right? 
#132 is updating it too and adding updated node_server to generator so i believe we can close this one.
