### ISSUE TITLE
Heroku Deployment :: Cannot find module "/app/react/index.js"(…)

### ISSUE THREAD

**Issue by fighella** [netguru/react_webpack_rails#137]
I am having an issue where I cannot find the /app/react/index.js file in production on Heroku.

The app runs as expected locally. 

"Uncaught Error: Cannot find module "/app/react/index.js""

**webpack.config**

```
module.exports = {
  entry: {
    main: ['/app/react/index.js']
  },
  output: {
    path: __dirname + '/app/assets/javascripts',
    filename: 'react_bundle.js'
  },
  module: {
    loaders: [
      {
        key: 'jsx',
        test: /\.jsx?$/,
        exclude: /(node_modules)/,
        loaders: ['babel']
      },
      {
        key: 'style',
        test: /\.s?css$/,
        loader: ExtractTextPlugin.extract('css!sass')
      }
    ]
  },
  resolve: {
    extensions: ['', '.js', '.jsx', '.js.jsx']
  },
  plugins: [
    new ExtractTextPlugin('../stylesheets/react_bundle.css', {
      allChunks: true
    })
  ]
};
```

**Comment by nekath** [comment]
You pointed to absolute path for entry file. Just change to relative path
`main: ['/app/react/index.js']` -> `main: ['./app/react/index.js']`

**Comment by fighella** [comment]
Uncaught Error: Cannot find module "./app/react/index.js"

I feel like Heroku isn't letting me see that path? :/

**Comment by fighella** [comment]
Hi @nekath - Sincere thanks for the reply.

Same issue with the relative path unfortunately.  

I understand perhaps this issue doesn't belong here -- but I have tried to add RWR to an existing project - and hopefully this is useful for anyone suffering the same issue.

**Comment by nekath** [comment]
Are you sure that the file lies under path `app/react/index.js` ?
We have few projects that are hosted on heroku and this default config works fine.

Heroku keeps whole repository in dyno so if the path is correctly defined in development (local) environment, it should also be found properly on heroku (relative path).

You should check again if the entry file exists and is with lower letters.

**Comment by fighella** [comment]
context: __dirname + '/app',
  entry: {
    main: './app/react/index.js'
  },

Solved. I added a context and removed the [] square bracked from my main entry and happy days.

Thanks everyone for your help.
