### ISSUE TITLE
Redux support?

### ISSUE THREAD

**Issue by liorbrauer** [netguru/react_webpack_rails#14]
Hi,

I was wondering if this gem can be used in conjunction with Redux? And if so, are there any available examples of how to do so?

For example, I would like to register an `App` component to be rendered on a rails view and wrap it inside a `<Provider>` like so:

```html
<Provider store={store}>
  <App />
</Provider>
```

Is this possible?

**Comment by mxaly** [comment]
Hi @liorbrauer 
Good news is that we are planning to use Redux as our default and we will work on integration for sure. Till now, you can see @marcinkornek [solution](https://github.com/marcinkornek/home-budget-rails-react-redux/blob/master/app/react/containers/budget-items.jsx)

**Comment by justin808** [comment]
Hi @liorbrauer, for a similar solution with Redux, React, Webpack, and Rails, check out:

* https://github.com/shakacode/react_on_rails/
* https://github.com/shakacode/react-webpack-rails-tutorial/

**Comment by lichtamberg** [comment]
@liorbrauer Maybe this helps you alos: http://www.lampesberger.net/blog/2016/03/16/react-slash-redux-with-rails-3-dot-2-and-sprockets/

**Comment by mxaly** [comment]
@lichtamberg we already have plugin for redux :) 
checkout here: https://github.com/netguru/rwr-redux
This plugin allows you to pass data to redux and share it between react components.
