### ISSUE TITLE
Injecting child components through `props.children`

### ISSUE THREAD

**Issue by mattmanske** [netguru/react_webpack_rails#144]
Really enjoying this integration so far. One roadblock that I'm running up against though: Is it possible to pass child components to the parent component through `props.children` when using the rails view helper? ie:

```
<%= react_component('NavList') do %>
  <a href="...">One</a>
  <%= react_component('Button', { link: 'two' }) %>
  ...
<% end %>
```

I would expect in the parent 'NavList' component that the block elements would be available via the `children` prop, but I'm not seeing them passed through anywhere in the parent component. 

Is this the supported with the current view helper, and if so, am I going about it incorrectly? Thanks

**Comment by mxaly** [comment]
Hello @mattmanske 
Nesting components is not supported and we were not planning to add this so far.

I was experimenting with this some time ago and found it a bit tricky to collect nested part of .erb template into html string on it's runtime (which is required in this case for nested html.erb code). Nesting another helper sounds even more complicated as it all need to be rendered into html elements that react is then mounting. 

Do your case somehow require this functionality?
