### ISSUE TITLE
TypeError: Turbolinks.pagesCached is not a function

### ISSUE THREAD

**Issue by aymericbouzy** [netguru/react_webpack_rails#145]
Hi,

I've just migrated to rails 5 and Turbolinks 5, and I'm getting the following error : 
```
TypeError: Turbolinks.pagesCached is not a function. (In 'Turbolinks.pagesCached(0)', 'Turbolinks.pagesCached' is undefined)
handleTurbolinksEvents — react_integration.self-3a8c3738149f193c4530c532283459b3b0f1a5cc701c1fef7da37d47b14aa6d4.js:71
reactMain — react_integration.self-3a8c3738149f193c4530c532283459b3b0f1a5cc701c1fef7da37d47b14aa6d4.js:84
Global Code — react_integration.self-3a8c3738149f193c4530c532283459b3b0f1a5cc701c1fef7da37d47b14aa6d4.js:88
```

Did I miss something, or is there no turbolinks 5 support yet? Which turbolinks version should I use with rails 5? Thanks!

**Comment by mxaly** [comment]
Which version of turbolinks you have? We were adding support for rails 5 and it was working just fine - see rails 5 app in specs https://github.com/netguru/react_webpack_rails/blob/master/spec/rails5_dummy_app/app/assets/javascripts/application.js

**Comment by aymericbouzy** [comment]
That's what I just saw indeed :/ I had specified `'~> 5.0.0'` which resolves to `5.0.1` at the moment if I'm not mistaken, and changing it to `'~> 5.x'` as it's done in specs doesn't solve it.

Maybe I did something wrong when migrating from rails 4.2 ...

**Comment by aymericbouzy** [comment]
I was still on RWR version 0.4.1 ... sorry for that, upgrading to latest version solves it.

**Comment by mxaly** [comment]
turbolinks are handler here:
https://github.com/netguru/react_webpack_rails/blob/master/lib/assets/javascripts/react_integration.js.erb#L19
you can cp this to your assets/javascripts directory and debug. 
Reading your error i think that it's not detecting your turbolinks as v4/v5
v5 events are pulled here: https://github.com/netguru/react_webpack_rails/blob/master/lib/assets/javascripts/react_integration.js.erb#L27-L28 
```
mountEvent = 'turbolinks:load';
unmountEvent = 'turbolinks:before-cache';```

**Comment by mxaly** [comment]
ok, good to know:)

**Comment by aymericbouzy** [comment]
Thanks for being so _react-ive_ ;)
