### ISSUE TITLE
Example/help with RWR.renderComponent

### ISSUE THREAD

**Issue by spherop** [netguru/react_webpack_rails#147]
Great gem.

Having trouble using the javascript RWR.renderComponent()**. See `RWR.renderComponent('App', appElement);` below.

When I use the rails helper `<%#= react_component('App') %>` in application.html.erb it works fine

application.html.erb
```
<body>
    <%= render 'layouts/react_hot_assets' %>
    <%= render "partials/header" %>
    <div id="app-container">
    </div>
    <%#= react_component('App') %> 
    .....
  </body>
```

index.js - here is where I am unsuccessfully trying to use renderComponent instead of the rails helper.
```
import RWR from 'react-webpack-rails';
RWR.run();

import App from './components/app';
RWR.registerComponent('App', App);

$(document).ready(function() {
    const appElement = $('#app-container');
    RWR.renderComponent('App', appElement);  // throws error here 
     ... Uncaught Error: _registerComponent(...): Target container is not a DOM element.
});

```

app.jsx
```
import React from 'react';
class App extends React.Component {
  render() {
    return(
      <div>
        foo
      </div>
    );
  }
}

export default App;
```

The target container error does not happen if I use the Rails helper instead of the JS registerComponent. 

Hope this is clear enough. Any thoughts appreciated.

**Comment by pewniak747** [comment]
@spherop I think that could happen since you're passing a jQuery object instead of native DOM node to `RWR.renderComponent`

Can you try:
```javascript
const appElement = document.getElementById('app-container'); // DOM node
RWR.renderComponent('App', appElement);
```
?

**Comment by spherop** [comment]
Thanks ... Yea that's where I was at first:

```
$(document).ready(function() {
    const appElement = document.getElementById('app-container'); // DOM node
    RWR.renderComponent('App', appElement);
});
```

still getting:

`Uncaught Error: _registerComponent(...): Target container is not a DOM element.`

**Comment by spherop** [comment]
well this works. still wrapping my head around things in this arena.

```
$(document).ready(function() {
  ReactDOM.render(
    <App store={ store } />,
    document.getElementById('app-container')
  );
});
```

My primary need was to pass in the `store` (mobx) and I couldn't see how to do something like that with the Rails helper approach.  Anyway, now seemingly unblocked and good to go. Thanks again @pewniak747...

**Comment by mxaly** [comment]
@spherop do you think that helper like the on from rwr-redux (https://github.com/netguru/rwr-redux#use-registered-store-and-components-in-rails-view) may be useful for mobx? If so, maybe you can take a look at the integrations/plugins api that we prepared here and create one - we are more than happy to help :)
