### ISSUE TITLE
Add environment variables/feature flags

### ISSUE THREAD

**Issue by marcinkornek** [netguru/react_webpack_rails#18]
Discussion moved from here: https://github.com/netguru/react_webpack_rails/pull/17#issuecomment-151733468 - what do you think ? Should we add variables in default configuration?
I mean sth like this:
```js
// dev.config.js
config.plugins.push(
  new webpack.DefinePlugin({
    __DEVELOPMENT__: true
  })
);
```
this variable/variables are available in whole application and can be used for example to enable developing tools. Usage is described https://webpack.github.io/docs/list-of-plugins.html#defineplugin and https://github.com/petehunt/webpack-howto#6-feature-flags .
But we can also pass anything from Rails, also environment:
```erb
<%= react_component(hello-world', { currentUser: current_user, env: Rails.env }) %>
```

**Comment by mxaly** [comment]
+1 for passing stuff from Rails

Our main goal with this gem and it's webpack config is to keep it simple and provide minimal , required configuration. This way developers can easily understand the it and modify when needed. Your solution with global variables is nice and i can be useful, but imo it should not be part of default configuration. Instead, it will be nice to have such example in docs/ wiki :) 

@nekath @Szeliga any thoughts on this?

**Comment by nekath** [comment]
:+1: for example in docs or even wiki

We can use configure block and add custom initializer with such options.
