### ISSUE TITLE
integrations flow

### ISSUE THREAD

**Issue by mxaly** [netguru/react_webpack_rails#25]
After refactor, both - js and ruby apis are prepared for modular integrations. It can be extracted into external gems. For now we have only react-router, [Alt](https://github.com/netguru/react_webpack_rails/pull/24) is almost ready, redeux is in progress. What do you think about such extraction? 

I personally think that we sohuld keep core integrations (router, most popular flux stuff) as part of gem and add description + example showing how other integrations can be done.

**Comment by marcinkornek** [comment]
Good idea :)

**Comment by nekath** [comment]
It's really good idea. I love namespaces, we should not be selfish and populate global namespace too much :)

But I don't want to type too much while using core methods.

What do you think about keeping core methods in global namspace but plugins specific ones under in theirs namespace?

example:

```
RWR.getComponent()
RWR.alt.getStore()
```

**Comment by nekath** [comment]
Merged in https://github.com/netguru/react_webpack_rails/pull/31
