### ISSUE TITLE
Server prerender option

### ISSUE THREAD

**Issue by AppyCat** [netguru/react_webpack_rails#4]
This gem is really good for webpack integration along with using the react-rails view helper.
I was wondering if the gem enables server side prerendering?

I tried it, it works, however when I do a curl call:

curl localhost:3000

I see the div for the component but not the html enclosed within it. I see the results in the browser too, but again just missing the html for the component in the source code of the page which would be very helpful for SEO.

Other than that 1 point the gem worked really smooth right out the gate. Really nice way to have best of both worlds.

**Comment by mxaly** [comment]
Hi @AppyCat 
thanks for you comments:)

We are not supporting server side render for now, but we are planning to add it. Work is in progress :)

**Comment by justin808** [comment]
@AppyCat, we've got server rendering with react and webpack working right now: Check out: http://reactrails.com and view the page source.

* https://github.com/shakacode/react_on_rails/
* https://github.com/shakacode/react-webpack-rails-tutorial/

**Comment by AppyCat** [comment]
Hi Justin,

Thank you so much for that update. Am checking right now.

Best regards,
Pardeep.

**Comment by AppyCat** [comment]
Hi Justin,

Would you recommend Redux for sure over alt.js?

Best regards,
Pardeep.

**Comment by mxaly** [comment]
@AppyCat i think that this is not the best place for such question
I'm using Alt and i like it a lot but redux have something that is kind of trend in flux world now - single store. Anyway, we are planning support for multiple flux implementations and we are working on making it's implementation easy and pluggable. Checkout [integrations flow](https://github.com/netguru/react_webpack_rails/issues/25) and [basic alt integration](https://github.com/netguru/react_webpack_rails/pull/24)

**Comment by hfwang** [comment]
Maybe the https://github.com/mjackson/react-stdio project would be good for keeping stuff loosely coupled?

(Runs the react server side renderer and exposes it via stdin/stdout)

**Comment by mxaly** [comment]
@hfwang we were looking at it but we have some plans for serverside executed code and react-stdio didn't fit into it. Anyway, thanks for suggestion :)

**Comment by mxaly** [comment]
solved in #42
