### ISSUE TITLE
Rendering Component instead of View

### ISSUE THREAD

**Issue by LordLambda** [netguru/react_webpack_rails#41]
This framework has been great, for allowing everything to be setup, and just kind of handled for us. It's meeting our needs for when we first started using React. However we're wanting to switch more to a react way while keeping the webpack/karma setup we have now.

While we could switch to react rails to render straight from our controllers, it'd be nice if this library supported what react_rails does. Perhaps this library does do it, and we just don't know.

Anyway for a real detail of what we want, inside react-rails it's possible to do the following:
```ruby
class TodoController < ApplicationController
  def index
    @todos = Todo.all
    render component: 'TodoList', props: { todos: @todos }, tag: 'span', class: 'todo'
  end
end
```

Which is nice for us because if we just want to render a component without scaffolding a view.

Is this currently possible with this framework? Is there something we're missing, or this just on the "TODO" list?

**Comment by mxaly** [comment]
Hi!
Love to hear that it's working well for you. :)

Our gem doesn't support `render component: ...` as yet, but this is a great idea and it's definitely in our TODO list. 
Currently, we are focused on server-side rendering and v1 release, so I can't tell when exactly we will be able to implement the idea. Anyways, we will do our best to deliver it to you in the near future. In the meantime, if you have resources, maybe you can start working on it? We would be appreciate that! :)

**Comment by mxaly** [comment]
Implementation started in: https://github.com/netguru/react_webpack_rails/pull/46
