### ISSUE TITLE
Generator fails if Gemfile includes Github gems

### ISSUE THREAD

**Issue by hajder** [netguru/react_webpack_rails#64]
In my Gemfile I have gems like this one

    gem 'auto_html', github: 'hajder/auto_html'

When trying to run the generator I get a following error

```
rails g react_webpack_rails:install --tmp-package
    generate  react_webpack_rails:install:core --tmp-package
git://github.com/hajder/auto_html.git (at master@c41a78b) is not yet checked out. Run `bundle install` first.
    generate  react_webpack_rails:install:hot_reload --tmp-package
git://github.com/hajder/auto_html.git (at master@c41a78b) is not yet checked out. Run `bundle install` first.
    generate  react_webpack_rails:install:server_side --tmp-package
git://github.com/hajder/auto_html.git (at master@c41a78b) is not yet checked out. Run `bundle install` first.
    generate  react_webpack_rails:install:karma_setup --tmp-package
git://github.com/hajder/auto_html.git (at master@c41a78b) is not yet checked out. Run `bundle install` first.
    generate  react_webpack_rails:install:example --server-side
git://github.com/hajder/auto_html.git (at master@c41a78b) is not yet checked out. Run `bundle install` first.
```

I did find [a mention of a similar problem](https://github.com/activeadmin/activeadmin/issues/2899#issuecomment-53453760) in ActiveAdmin issue tracker and a solution proposed there did solve it for me. By running `bundle install --deployment` before the generator I was able to get it to work.

I didn't get to the bottom of this issue yet though.

**Comment by mibamur** [comment]
Run `bundle install` first. )))

**Comment by hajder** [comment]
@mibamur I don't think you took time to read through what I wrote and what is explained in the linked issue.

**Comment by mxaly** [comment]
hi @hajder I can't reproduce this. Can you share more details? rben or rvm? bundler wersion etc?

**Comment by hajder** [comment]
I don't have time to dig into it right now so I'm closing it now. If anyone else has the same problem we can always reopen.

**Comment by mxaly** [comment]
Thanks @hajder.
