### ISSUE TITLE
React Router Server Render

### ISSUE THREAD

**Issue by murtali** [netguru/react_webpack_rails#65]
Is there a way to prerender / server side using while using react router?
How can you pass props to react-router via the react_router api method

**Comment by murtali** [comment]
Sorry -> just found https://github.com/netguru/react_webpack_rails/blob/master/docs/api.md#react_router


My question now would be->

Is there a way to prerender / server side render using while using react router?

**Comment by mxaly** [comment]
Hi @murtali 

It's not implemented yet. 
We are planning to extract react-router integration into external plugin and add server side support there. There are also few problems that we need to solve like handling redirects, handling unmatched routes etc before release. 
I was able to run server side routing on my experimental env so if you need this functionality now, let me know and i will share this very alpha solution with you.

When it comes to passing props - i need to check react-router v2 - it may be added there. In v1 however, the only solution that that worked was to create a wrapper component and pass props to it. 
Handling props is also in our roadmap for react-router integration and again - if you need it now let me know so i can share temporary workaround with you.

**Comment by mxaly** [comment]
moving this to https://github.com/netguru/rwr-react_router/issues/2 and closing.
