### ISSUE TITLE
Syntax error with fat arrow

### ISSUE THREAD

**Issue by jerefrer** [netguru/react_webpack_rails#7]
Sorry to bother you again, but after all you just wrote an article inviting people to try out a whole new universe of tools they didn't know before (webpack, npm, react, es6) ;)

I'm trying to use [react-google-maps](https://github.com/tomchentw/react-google-maps) in my project and they explain to define the map click action like this `_handle_map_click = (event) => {`. But then webpack complains and says `Unexpected token` pointing to the `=` sign.

I thought maybe this fat arrow stuff is still experimental and tried adding `stage: 0` to the webpack config, but it still doesn't work:

    module: {
      loaders: [
        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          loader: 'babel-loader',
          query: {
            stage: 0
          }
        },
        ...

Any idea ?

**Comment by jerefrer** [comment]
Actually even using the `=` sign inside the class definition breaks:

    class Map extends React.Component {
      state = {...}
    }

raises `Unexpected token` as well.

**Comment by jerefrer** [comment]
Mmmh ok it turns out I just needed to stop `npm start` and re-run again. I thought I had done it but I somehow may have mixed two steps together :)

Anyway don't you think it would be a good idea to add the `stage: 0` option by default in the gem ?

**Comment by Szeliga** [comment]
I don't recommend using Stage 0 in any production app. I've added a PR that creates a `.babelrc` file with the following contents:
```
{
  "stage": 1
}

```

If you want to use Stage 0, you can change it here.

Best regards, Szymon Szeliga

**Comment by jerefrer** [comment]
Good advice. Also I didn't know about the existence of `.babelrc`. Thank you !
