### ISSUE TITLE
Inform about missing integration handler with proper error

### ISSUE THREAD

**Issue by mxaly** [netguru/react_webpack_rails#70]
Now, there is `Uncaught Invariant Violation: ReactDOM.render(): Invalid component element.` which says nothing about the missing integration. 

https://github.com/netguru/react_webpack_rails/blob/master/js/src/integrations-manager.js#L13

**Comment by caspg** [comment]
https://github.com/netguru/react_webpack_rails/pull/71/

**Comment by caspg** [comment]
PR merged to master. Released in v0.3.1
