### ISSUE TITLE
ReferenceError: RWR is not defined

### ISSUE THREAD

**Issue by 33volcanoes** [netguru/react_webpack_rails#72]
Hello,

I'm trying to test a hole feature with capybara, but the react component never gets rendered.

Getting the following error on the console. ReferenceError: RWR is not defined

On development all is working fine.

**Comment by mxaly** [comment]
Hello @33volcanoes 

Please make sure you are running `npm run build` before running specs. We are using capybara for feature testing too. For eg. [here](https://github.com/netguru/react_webpack_rails/blob/master/spec/rails4_dummy_app/spec/features/client_side_hello_world_spec.rb) 
You can take a look at [Rakfefile](https://github.com/netguru/react_webpack_rails/blob/master/Rakefile) too for more details. 

Le me know if those examples help.

**Comment by 33volcanoes** [comment]
@mxaly  thank you for your help, i will try, dont know why is not rendering the component on tests.

**Comment by 33volcanoes** [comment]
I discover the problem, i think capybara-webkit have issues rendering react, i change the spec to use driver: :selenium, and works!!

**Comment by mxaly** [comment]
Good to hear that:)

**Comment by 33volcanoes** [comment]
Thanks for your help, also discover, that somethimes rails cache assets on test, so i use 

rake assets:clobber RAILS_ENV=test

and works.

**Comment by DidiRaggio** [comment]
Hi I'm getting the same error when running in production or development.
application-69b0603….js:8 Uncaught ReferenceError: RWR is not defined
Any help would be greatly appreciated!

**Comment by fighella** [comment]
@DidiRaggio did  you solve? I have same issue now

**Comment by mxaly** [comment]
@DidiRaggio & @fighella can you check if there is react_bundle.js generated on your machine and it's not empty?

**Comment by fighella** [comment]
It is generated locally. But not on Heroku.

**Comment by mxaly** [comment]
@fighella did you have chance to check this guide: https://github.com/netguru/react_webpack_rails/blob/master/docs/deployment.md ? 
are there any errors during deployment?
