### ISSUE TITLE
turbolinks 5 fix

### ISSUE THREAD

**Issue by mibamur** [netguru/react_webpack_rails#76]
Hello!

turbolinks 5 came with some new events and methods 

this
https://github.com/netguru/react_webpack_rails/blob/d0cd49e2fe518d4f78a233a6ab48558713b94bfa/lib/assets/javascripts/react_integration.js.erb#L71

that
https://github.com/turbolinks/turbolinks/issues/36

**Comment by mxaly** [comment]
Thanks for rising this up @mibamur 

We will update integration soon so it will support Turbolinks 5. It's already implemented so if you need this functionality now, you can override `app/assets/javasciprts/react_integartion.js.erb` with: https://github.com/netguru/react_webpack_rails/blob/turbolinks_5/lib/assets/javascripts/react_integration.js.erb or wait for new release. 

Additionally, we have added rails5 specs (#90) to make sure that rwr is compatible with it.
