### ISSUE TITLE
css-loader not included in default generated package.json

### ISSUE THREAD

**Issue by dbackeus** [netguru/react_webpack_rails#83]
`Module not found: Error: Cannot resolve module 'css' in...`

Fixed by `npm install css-loader --save-dev`

Though I'm a bit confused about whether to save dev or save as a runtime dependency since the default package.json has a lot of build packages not under devDependencies. Haven't gotten as far as deploying yet.

Normally these sort of dependencies are development only.

**Comment by dbackeus** [comment]
Also on the topic of css. I'm not sure how to hot reload css. `npm run start-hot-dev` doesn't emit the css file at all while `npm start` does.

Is the point to use css modules or something like that rather than a separate css file or can I get hot reloading some other way?

**Comment by mxaly** [comment]
@dbackeus thanks for rising this up.
We made build related dependencies not part of dev dependencies to avoid problems with building on production. Depending on chosen flow, build can be part of deploy process and can be done on CI or on production server. Looks like it's time to rethink this.

**Comment by mxaly** [comment]
Regarding `npm run start-hot-dev` not serving css - let me investigate.

**Comment by dbackeus** [comment]
Yeah I had a feeling the default behaviour of heroku build pack would be to not install `devDependencies` and thus fail to build assets. I think that's a valid enough reason to keep the necessary packages under `dependencies` but would be nice to have it documented somewhere.

Looking forward to any news regarding the css :+1:

**Comment by mxaly** [comment]
@dbackeus looks like we forget about css-loader while implementing hot reload :D 

anyway, it's easy to fix this: just add in your `webpack/hot-dev-config.js`:

```js
var scssLoader = config.module.loaders.filter(function(loader) { return loader.key == 'scss' })[0]
scssLoader.loader = 'style!css!sass!';
```

We will update generator soon:)

**Comment by dbackeus** [comment]
Thanks, the fix did the trick!

**Comment by mxaly** [comment]
#84
