### ISSUE TITLE
Forcing production env when building

### ISSUE THREAD

**Issue by dbackeus** [netguru/react_webpack_rails#86]
After deploying to Heroku I noticed that I was getting warnings that react had been compiled in development mode.

I could fix this by adding the following to production.config.js:

```js
config.plugins.push(
  new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': '"production"'
    }
  })
);
```

(got the idea from http://moduscreate.com/optimizing-react-es6-webpack-production-build/)

Shouldn't something like this be there by default or am I missing something?

**Comment by mxaly** [comment]
@dbackeus thanks for point this out and providing solution. It should be set by default. We have updated generator.

**Comment by dbackeus** [comment]
👍
