### ISSUE TITLE
Error: React.createElement: type should not be null

### ISSUE THREAD

**Issue by kalashnikovisme** [netguru/react_webpack_rails#94]
Development mode.

After

```
rails g react_webpack_rails:install
npm start
```

I see this error in js-console.
NOTE: There's not any react-js code.

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).warning
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

Problem at react_integration. Line 53.

**Comment by mxaly** [comment]
Looks like there is some DOM node (probably generated by react_component helper that integrations is trying to mount. 

checkout: https://github.com/netguru/react_webpack_rails/blob/master/docs/install_generator.md
install generator adds example controller by default.

**Comment by kalashnikovisme** [comment]
@mxaly you're right. Thanks!
