### ISSUE TITLE
How to use images in css

### ISSUE THREAD

**Issue by dbackeus** [netguru/react_webpack_rails#95]
Noticed that the usual rails trick of using `image-url` for `background-image` in scss files didn't play well with webpack.

The Heroku build log states: `SassC::SyntaxError: Error: error in C function image-url: undefined method `[]' for nil:NilClass`

And the hot reloading environment just ignores it altogether.

Any ideas for how to properly use image assets + scss?

**Comment by mxaly** [comment]
i think that it's similar case like https://github.com/netguru/react_webpack_rails/issues/61 
You need to use full path to get the images work and disable digest assets for them

**Comment by dbackeus** [comment]
Yes, this clears things up, thank you!
