### ISSUE TITLE
undefined method `react_component'

### ISSUE THREAD

**Issue by djdawson3** [netguru/react_webpack_rails#98]
Hi,

I'm trying to get this running on an ubuntu host. I encountered a couple issues prior to this one:

1. I had to create an empty .foreverignore file in the react folder for the node server to start properly.
2. I was getting ERRNOSPC errors when I was starting the node server, so to fix it I had to run the following command: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

Now, whenever I try to load the example located at /react_examples/component, I get the following error: 

undefined method `react_component' for #<#<Class:0x0000000564a9d8>:0x00000005599bd8>

Is there some additional setup that I'm missing that would resolve this reference?

**Comment by mxaly** [comment]
Hi @djdawson3 

Can you share a bit more context? I was able to setup and run without any problems on ubuntu and debian. 

Where are you using `react_component` is it Rails view?

**Comment by mxaly** [comment]
@djdawson3 have you restarted your server after bundle install? It may be the reason why helper is missing.

**Comment by djdawson3** [comment]
Hi mxaly,

It must have been that. I've since restarted my development environment and the issue is no longer present. That's dumb, I should definitely have tried that and I can't believe I forgot.  I'll go ahead and resolve this. 

Thanks.
